### How to use this document
# 1. Fill in your info
# 2. Re-excecute the build in the command line with: bundle exec jekyll serve
# 3. Push to github
# NOTE: it looks like you need to rebuild + repush everytime you update this _config.yml file


### Site Settings ###
title               : IS445 Data viz homework
description         : >-
                      I am a corgi!
baseurl             : ""   # Change to empty quotes if you are hosting your site at <your-username>.github.io directly,
#                                             otherwise will be hosted at <your-username>.github.io/{{base_url}}
repository          : yvonneyangyan  # Change to <your-username> for github OR, if that doesn't work <your-username>/<your-username>.github.io (or remove it if you don't need remote projects) -- for example, I would put "jnaiman" without the quotes after the ":" here


collections:
  posts:
    output: true
permalink: /_posts/data-viz-homework

### Plugins ###
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Yvonne112 Yang
###  image             : https://media.tenor.com/8RcIoWTKYR4AAAAe/scuze-corgi.png
#  behance           : yvonneyangyan
# dribbble          : yvonneyangyan
  email             : yvonneyangyan@domain.com
#  facebook          : yvonne yang
  github            : yvonneyangyan # JPN
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
#  twitch            : your_username
  twitter           : your_username
#  vimeo             : your_username
  youtube           : your_channel_name
# keybase           : your_username



### Exclude from processing ###
## Add yours here if you have other stuff in your github.io page!!!**
exclude:
  - README.md
  - README.md~
  - CONTRIBUTING.md
  - LICENSE.md
  - LICENSE.md~
  - config.yml~
  - "*.log"
  - "python_notebooks/*"
