### How to use this document
# 1. Fill in your info
# 2. Re-excecute the build in the command line with: bundle exec jekyll serve
# 3. Push to github
# NOTE: it looks like you need to rebuild + repush everytime you update this _config.yml file


layout: post
title: Data Visualization Homework
description: Altair + Python Visualizations
date: 2024-11-24
theme: minima
posts:
  output: true


### Plugins ###
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Yvonne1 Yang
###  image             : https://media.tenor.com/8RcIoWTKYR4AAAAe/scuze-corgi.png
#  behance           : your_username
# dribbble          : your_username
  email             : username@domain.com
#  facebook          : your_username
  github            : jnaiman # JPN
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
#  twitch            : your_username
  twitter           : your_username
#  vimeo             : your_username
  youtube           : your_channel_name
# keybase           : your_username




### Exclude from processing ###
## Add yours here if you have other stuff in your github.io page!!!**
exclude:
  - README.md
  - README.md~
  - CONTRIBUTING.md
  - LICENSE.md
  - LICENSE.md~
  - config.yml~
  - "*.log"
  - building_visualizations.ipynb
  - _posts/data-viz-homework.md
  - "python_notebooks/*"
